package docsgen

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

func header(source string) []byte {
	return []byte(fmt.Sprintf("<!-- GENERATED by fast-agent-harness docsgen; do not edit. Source: %s -->\n\n", source))
}

func sourceHashFooter(data any) ([]byte, error) {
	hash, err := sourceHash(data)
	if err != nil {
		return nil, err
	}
	return []byte(fmt.Sprintf("\n<!-- source-hash: %s -->\n", hash)), nil
}

func sourceHash(data any) (string, error) {
	body, err := json.Marshal(data)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(body)
	return hex.EncodeToString(sum[:]), nil
}

func markdownTable(headers []string, rows [][]string) string {
	widths := make([]int, len(headers))
	for i, header := range headers {
		widths[i] = len(header)
	}
	escapedRows := make([][]string, 0, len(rows))
	for _, row := range rows {
		cells := make([]string, len(headers))
		for i := range headers {
			if i < len(row) {
				cells[i] = escapeTableCell(row[i])
			} else {
				cells[i] = "-"
			}
			if len(cells[i]) > widths[i] {
				widths[i] = len(cells[i])
			}
		}
		escapedRows = append(escapedRows, cells)
	}
	var b strings.Builder
	writeTableRow(&b, headers, widths)
	separators := make([]string, len(headers))
	for i, width := range widths {
		if width < 3 {
			width = 3
		}
		separators[i] = strings.Repeat("-", width)
	}
	writeTableRow(&b, separators, widths)
	for _, row := range escapedRows {
		writeTableRow(&b, row, widths)
	}
	return b.String()
}

func writeTableRow(b *strings.Builder, cells []string, widths []int) {
	b.WriteString("|")
	for i, cell := range cells {
		fmt.Fprintf(b, " %-*s |", widths[i], cell)
	}
	b.WriteString("\n")
}

func escapeTableCell(value string) string {
	value = strings.ReplaceAll(value, "\n", " ")
	value = strings.ReplaceAll(value, "|", `\|`)
	value = strings.TrimSpace(value)
	if value == "" {
		return "-"
	}
	return value
}

func fencedJSON(raw []byte) string {
	var out bytes.Buffer
	if err := json.Indent(&out, raw, "", "  "); err != nil {
		return strings.TrimSpace(string(raw))
	}
	return out.String()
}

func sortedStrings(in []string) []string {
	out := append([]string(nil), in...)
	sort.Strings(out)
	return out
}
