package gateway

func (s *Server) routes() {
	s.mux.HandleFunc("GET /health", s.handleHealth)
	s.mux.HandleFunc("GET /ready", s.handleReadiness)
	s.mux.HandleFunc("GET /v1/auth/status", s.handleAuthStatus)
	s.mux.HandleFunc("POST /v1/auth/deepseek", s.handleDeepSeekAuth)
	s.mux.HandleFunc("POST /v1/auth/codex/import", s.handleCodexImport)
	s.mux.HandleFunc("GET /v1/config", s.handleConfigStatus)
	s.mux.HandleFunc("GET /v1/benchmarks", s.handleBenchmarks)
	s.mux.HandleFunc("GET /v1/tools", s.handleTools)
	s.mux.HandleFunc("GET /v1/mcp", s.handleMCP)
	s.mux.HandleFunc("GET /v1/processes", s.handleManagedProcesses)
	s.mux.HandleFunc("POST /v1/run", s.handleRun)
	s.mux.HandleFunc("GET /v1/sessions", s.handleListSessions)
	s.mux.HandleFunc("POST /v1/sessions", s.handleCreateSession)
	s.mux.HandleFunc("GET /v1/sessions/{id}", s.handleGetSession)
	s.mux.HandleFunc("GET /v1/sessions/{id}/status", s.handleSessionStatus)
	s.mux.HandleFunc("GET /v1/sessions/{id}/context", s.handleSessionContextStatus)
	s.mux.HandleFunc("GET /v1/sessions/{id}/inspect", s.handleSessionInspect)
	s.mux.HandleFunc("GET /v1/sessions/{id}/events", s.handleSessionEvents)
	s.mux.HandleFunc("POST /v1/sessions/{id}/inputs", s.handleSessionInput)
	s.mux.HandleFunc("POST /v1/sessions/{id}/inputs/{input_id}/complete", s.handleSessionInputComplete)
	s.mux.HandleFunc("POST /v1/sessions/{id}/run", s.handleSessionRun)
	s.mux.HandleFunc("POST /v1/sessions/{id}/user_input/{request_id}/answer", s.handleUserInputAnswer)
	s.mux.HandleFunc("POST /v1/sessions/{id}/user_input/{request_id}/reject", s.handleUserInputReject)
	s.mux.HandleFunc("POST /v1/sessions/{id}/undo", s.handleSessionUndo)
	s.mux.HandleFunc("POST /v1/sessions/{id}/redo", s.handleSessionRedo)
	s.mux.HandleFunc("POST /v1/sessions/{id}/cancel", s.handleSessionCancel)
}
