package config

import "time"

type Config struct {
	Provider                      string
	Model                         string
	Profile                       string
	BaseURL                       string
	APIKeyEnv                     string
	CredentialFile                string
	CodexBaseURL                  string
	CodexAuthFile                 string
	CodexRefreshURL               string
	CodexAuthAPIBaseURL           string
	CodexClientID                 string
	CodexOriginator               string
	Thinking                      string
	ReasoningEffort               string
	DisableSpark                  bool
	MaxTokens                     int
	MaxToolRounds                 int
	MaxParallelTools              int
	ProviderMaxRetries            int
	ContextWindowTokens           int64
	ContextCompactTokens          int
	ContextCompactKeep            int
	ContextCompactMaxChars        int
	ContextCompactStrategy        string
	ContextCompactSummaryProvider string
	ContextCompactSummaryModel    string
	WebSummaryMode                string
	WebSummaryProvider            string
	WebSummaryModel               string
	WebSummaryMaxInputTokens      int
	WebSummaryMaxOutputTokens     int
	WebSummaryTimeout             time.Duration
	WebCacheEnabled               bool
	WebCacheTTL                   time.Duration
	WebCacheMaxBytes              int64
	RequestTimeout                time.Duration
	StreamIdleTimeout             time.Duration
	WorkspaceRoots                []string
	ProjectDocMaxBytes            int
	ProjectDocFallbacks           []string
	MaxToolOutputBytes            int
	AutoApproveDangerous          bool
	StoreReasoningContent         bool
	GatewayAddr                   string
	MCPEnabled                    bool
	MCPConfigFiles                []string
	MCPAllowedServers             []string
	MCPServers                    []MCPServer
	HooksEnabled                  bool
	HookConfigFiles               []string
	Hooks                         []Hook
}
